// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheReynoldsGroupSite.Data;

#nullable disable

namespace TheReynoldsGroupSite.Migrations
{
    [DbContext(typeof(TheReynoldsGroupSiteContext))]
    [Migration("20220228014941_Tablesdata")]
    partial class Tablesdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TheReynoldsGroupSite.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryDescription")
                        .HasColumnType("int");

                    b.Property<int>("CategoryTypevalue")
                        .HasColumnType("int");

                    b.Property<string>("NegOneToNegTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NegThreeToNegFour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SixToFour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenToSeven")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThreeToOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalValuesFromQuestions")
                        .HasColumnType("int");

                    b.Property<string>("Zero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("TheReynoldsGroupSite.Data.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("TheReynoldsGroupSite.Data.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachId"), 1L, 1);

                    b.Property<string>("CoachFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoachLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoachType")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("CoachId");

                    b.ToTable("Coach");
                });

            modelBuilder.Entity("TheReynoldsGroupSite.Data.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AskQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssessmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<int?>("Likley")
                        .HasColumnType("int");

                    b.Property<int?>("MostLikely")
                        .HasColumnType("int");

                    b.Property<int?>("MostUnlikely")
                        .HasColumnType("int");

                    b.Property<int?>("Neutral")
                        .HasColumnType("int");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Unlikely")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Question");
                });
#pragma warning restore 612, 618
        }
    }
}
